import os
import base64
from typing import Optional

from logger import logger


async def send_email(
    to_email: str,
    company_url: str,
    pdf_bytes: bytes,
    synthesis: Optional[dict] = None,
) -> dict:
    api_key = os.getenv("RESEND_API_KEY")
    if not api_key:
        logger.error("RESEND_API_KEY not configured")
        return {"status": "failed", "error": "RESEND_API_KEY not configured"}

    try:
        import resend
        resend.api_key = api_key

        pdf_base64 = base64.b64encode(pdf_bytes).decode()

        company_name = company_url.replace("https://", "").replace("http://", "").split("/")[0]

        html_body = f"""
        <h1>Intel Brief: {company_name}</h1>
        <p>Your intelligence report for <strong>{company_name}</strong> is attached as a PDF.</p>
        <p>This report was generated by InstaRecon's multi-agent intelligence platform.</p>
        """

        if synthesis:
            insights = synthesis.get("insights", [])
            if insights:
                html_body += "<h2>Key Insights</h2><ul>"
                for insight in insights[:3]:
                    text = insight.get("text", "") if isinstance(insight, dict) else ""
                    html_body += f"<li>{text}</li>"
                html_body += "</ul>"

        html_body += """
        <hr>
        <p style="color: #666; font-size: 12px;">
          Generated by InstaRecon — Multi-Agent Intelligence Platform
        </p>
        """

        params = {
            "from": "InstaRecon <intel@instarecon.dev>",
            "to": [to_email],
            "subject": f"Intel Brief: {company_name}",
            "html": html_body,
            "attachments": [
                {
                    "filename": f"intel-brief-{company_name}.pdf",
                    "content": pdf_base64,
                }
            ],
        }

        response = resend.Emails.send(params)
        email_id = getattr(response, "id", str(response)) if response else None
        logger.info(f"Email sent to {to_email}: id={email_id}")
        return {"status": "sent", "email_id": email_id}

    except ImportError:
        logger.error("resend package not installed")
        return {"status": "failed", "error": "resend package not installed"}
    except Exception as e:
        logger.error(f"Failed to send email to {to_email}: {e}")
        return {"status": "failed", "error": str(e)}
