import os
import base64
import json
import ssl
from typing import Optional
from urllib.request import Request, urlopen
from urllib.error import URLError
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
import smtplib

from logger import logger


def _build_html_body(company_name: str, synthesis: Optional[dict]) -> str:
    body = f"""
    <h1>Intel Brief: {company_name}</h1>
    <p>Your intelligence report for <strong>{company_name}</strong> is attached as a PDF.</p>
    <p>This report was generated by InstaRecon's multi-agent intelligence platform.</p>
    """
    if synthesis:
        insights = synthesis.get("insights", [])
        if insights:
            body += "<h2>Key Insights</h2><ul>"
            for insight in insights[:3]:
                text = insight.get("text", "") if isinstance(insight, dict) else ""
                body += f"<li>{text}</li>"
            body += "</ul>"
    body += """
    <hr>
    <p style="color: #666; font-size: 12px;">
      Generated by InstaRecon — Multi-Agent Intelligence Platform
    </p>
    """
    return body


def _send_via_smtp(
    to_email: str, subject: str, html_body: str, pdf_bytes: bytes,
) -> dict:
    host = os.getenv("SMTP_HOST")
    if not host:
        return {"status": "failed", "error": "SMTP not configured — set SMTP_HOST in .env.local"}

    port = int(os.getenv("SMTP_PORT", "587"))
    user = os.getenv("SMTP_USER", "")
    password = os.getenv("SMTP_PASSWORD", "")
    from_addr = os.getenv("SMTP_FROM", user or "noreply@instarecon.dev")

    msg = MIMEMultipart()
    msg["From"] = from_addr
    msg["To"] = to_email
    msg["Subject"] = subject
    msg.attach(MIMEText(html_body, "html"))

    attachment = MIMEBase("application", "pdf")
    attachment.set_payload(pdf_bytes)
    encoders.encode_base64(attachment)
    attachment.add_header("Content-Disposition", "attachment", filename=subject.replace(" ", "_") + ".pdf")
    msg.attach(attachment)

    use_tls = os.getenv("SMTP_TLS", "true").lower() == "true"

    try:
        if use_tls:
            with smtplib.SMTP(host, port, timeout=15) as server:
                server.starttls(context=ssl.create_default_context())
                if user and password:
                    server.login(user, password)
                server.sendmail(from_addr, [to_email], msg.as_string())
        else:
            with smtplib.SMTP_SSL(host, port, timeout=15) as server:
                if user and password:
                    server.login(user, password)
                server.sendmail(from_addr, [to_email], msg.as_string())

        logger.info(f"Email sent to {to_email} via SMTP ({host})")
        return {"status": "sent", "email_id": None}
    except Exception as e:
        logger.error(f"SMTP error for {to_email}: {e}")
        return {"status": "failed", "error": f"SMTP error: {e}"}


def _send_via_resend(to_email: str, subject: str, html_body: str, pdf_bytes: bytes) -> dict:
    api_key = os.getenv("RESEND_API_KEY")
    if not api_key:
        return {"status": "failed", "error": "RESEND_API_KEY not configured"}

    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE

    pdf_base64 = base64.b64encode(pdf_bytes).decode()

    payload = json.dumps({
        "from": "InstaRecon <noreply@nautalaupr.resend.app>",
        "to": [to_email],
        "subject": subject,
        "html": html_body,
        "attachments": [
            {
                "filename": f"{subject}.pdf",
                "content": pdf_base64,
            }
        ],
    }).encode()

    req = Request(
        "https://api.resend.com/emails",
        data=payload,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
    )

    resp = urlopen(req, context=ctx, timeout=30)
    data = json.loads(resp.read().decode())
    email_id = data.get("id")
    logger.info(f"Email sent to {to_email} via Resend: id={email_id}")
    return {"status": "sent", "email_id": email_id}


async def send_email(
    to_email: str,
    company_url: str,
    pdf_bytes: bytes,
    synthesis: Optional[dict] = None,
) -> dict:
    company_name = company_url.replace("https://", "").replace("http://", "").split("/")[0]
    subject = f"Intel Brief: {company_name}"
    html_body = _build_html_body(company_name, synthesis)

    smtp_host = os.getenv("SMTP_HOST")
    resend_key = os.getenv("RESEND_API_KEY")

    if smtp_host:
        return _send_via_smtp(to_email, subject, html_body, pdf_bytes)

    if resend_key:
        try:
            return _send_via_resend(to_email, subject, html_body, pdf_bytes)
        except URLError as e:
            logger.error(f"Resend API error for {to_email}: {e.reason}")
            return {"status": "failed", "error": f"Resend unavailable ({e.reason}). To send email, set SMTP_HOST in .env.local to use your own email server."}
        except Exception as e:
            logger.error(f"Resend error for {to_email}: {e}")
            return {"status": "failed", "error": f"Resend error: {e}"}

    return {"status": "failed", "error": "No email provider configured. Set SMTP_HOST or RESEND_API_KEY in .env.local."}
