import os
from pathlib import Path
from datetime import datetime, timezone
from typing import Optional

from jinja2 import Environment, FileSystemLoader

from models import SynthesisOutput
from logger import logger


TEMPLATE_DIR = Path(__file__).resolve().parent / "templates"
env = Environment(loader=FileSystemLoader(str(TEMPLATE_DIR)))


def _serialize_synthesis(synthesis: Optional[dict]) -> Optional[dict]:
    if not synthesis:
        return None
    return {
        "insights": synthesis.get("insights", []),
        "risks": synthesis.get("risks", []),
        "opportunities": synthesis.get("opportunities", []),
    }


def _serialize_telemetry(telemetry: dict) -> dict:
    result = {}
    for service, record in telemetry.items():
        if hasattr(record, "model_dump"):
            result[service] = record.model_dump()
        else:
            result[service] = record
    return result


async def generate_pdf(
    url: str,
    agent_data: dict[str, dict],
    synthesis: Optional[dict],
    sponsor_telemetry: dict,
) -> bytes:
    company_name = url
    for aid, ad in agent_data.items():
        data = ad.get("data", {}) or {}
        if isinstance(data, dict):
            cn = data.get("company_name") or data.get("name") or ""
            if cn:
                company_name = cn
                break

    synthesis_dict = _serialize_synthesis(synthesis)
    telemetry_dict = _serialize_telemetry(sponsor_telemetry)

    template = env.get_template("intel_brief.html")
    html = template.render(
        company_name=company_name,
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        duration_seconds=30,
        executive_summary="Intel Brief generated by InstaRecon's multi-agent intelligence platform. This report combines findings from all 7 specialized agents with cross-signal synthesis.",
        synthesis=synthesis_dict,
        agent_reports=agent_data,
        sponsor_attribution=telemetry_dict,
    )

    try:
        from weasyprint import HTML
        pdf_bytes = HTML(string=html).write_pdf()
        return pdf_bytes
    except ImportError:
        logger.error("weasyprint not installed")
        raise
    except Exception as e:
        logger.error(f"weasyprint PDF generation failed: {e}")
        raise
